### ISSUE TITLE
Example fails

### ISSUE THREAD

**Issue by chevdor** [pocesar/node-nxt-api#3]
Hello,

The example does not seem to work fine.
Using
```
var NXT = require('nxt-api');

// start your NRS client first
var API = new NXT.API('http://<server>:<port>');

API.getNextBlockGenerators().then(function (answer) {
    console.log(answer);
});

API.rsConvert({ account: 'x' }).then(function (answer) {
    // should error
}, function (error) {
    console.log(error);
});
```
does return ```{ errorCode: 4, errorDescription: 'Incorrect "account"' }```. That makes sense.

However:
```
var NXT = require('nxt-api');

// start your NRS client first
var API = new NXT.API('http://<server>:<port>');

API.getNextBlockGenerators().then(function (answer) {
    console.log(answer);
});

API.rsConvert({ account: '<Valid Numeric Account ID>' }).then(function (answer) {
    // should error
}, function (error) {
    console.log(error);
});
```
returns 
```
Unhandled rejection Error: [object Object]
    at Object.ensureErrorObject (/Users/will/Dropbox/Projects/nxt/api-tests/node_modules/nxt-api/node_modules/bluebird/js/main/util.js:226:20)
    at Promise._rejectCallback (/Users/will/Dropbox/Projects/nxt/api-tests/node_modules/nxt-api/node_modules/bluebird/js/main/promise.js:427:22)
    at /Users/will/Dropbox/Projects/nxt/api-tests/node_modules/nxt-api/node_modules/bluebird/js/main/promise.js:445:17
    at Request._callback (/Users/will/Dropbox/Projects/nxt/api-tests/node_modules/nxt-api/nxt-api.js:83:33)
    at Request.self.callback (/Users/will/Dropbox/Projects/nxt/api-tests/node_modules/nxt-api/node_modules/request/request.js:344:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/will/Dropbox/Projects/nxt/api-tests/node_modules/nxt-api/node_modules/request/request.js:1239:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/will/Dropbox/Projects/nxt/api-tests/node_modules/nxt-api/node_modules/request/request.js:1187:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by pocesar** [comment]
hello, can you dump the object that is giving the error? Since it seems that an exception is being thrown (instead of an standard rejection), it seems to be coming from `request` library. you can rethrow the error doing:

```js
API.rsConvert({ account: '<Valid Numeric Account ID>' }).done(function (answer) {
    // should error
});
```

**Comment by chevdor** [comment]
If I look at the variable value in bluebird/util.js, I get:
```{"errorCode":1,"errorDescription":"Incorrect request"}```

If I print the value of answer however, I do get an object:
```
{ requestProcessingTime: 1,
  accountRS: 'the address',
  account: 'the numeric id' }
```

**Comment by pocesar** [comment]
I think I'll have to create a custom Error to differentiate from API errors and request errors (it may return 500 depending on how fast you query NXT)

**Comment by chevdor** [comment]
:+1: 
I am not running the client locally but on a RPi. When I connect the the client on the RPi via http, that works fairly fast. I don´t think it can timeout.

**Comment by pocesar** [comment]
ah, then I think it's a problem with CORS setting, try changing it to see if helps

**Comment by chevdor** [comment]
Ah good point. I will check that out and let you know.

**Comment by chevdor** [comment]
Hi,

I am testing in node and not in the browser so I don´t think this is CORS related. I also tested on localhost and I get the same issue.

Overall, I can call the API without any issue except for the ```getNextBlockGenerators``` method.
This is the method that fail in the sample.
